openapi: 3.0.0
info:
  title: Promoter API
  version: 1.0.0
servers:
  - url: https://promoter-api.test
paths:
  /api/promoters/:
    get:
      tags:
        - default
      summary: List Promoters
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Create Promoter
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                first_name: John
                last_name: Doe
                birthday_date: '1990-05-15'
                gender: male
                email: john.doe@example.com
                phone: '+4915123456789'
                address: 123 Promoter Lane, Berlin, Germany
                availabilities:
                  - Monday
                  - Wednesday
                  - Friday
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/promoters/{promoter_id}:
    get:
      tags:
        - default
      summary: Show Promoter
      parameters:
        - name: promoter_id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - default
      summary: Update Promoter
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                first_name: John
                last_name: Doe
                birthday_date: '1990-05-15'
                gender: male
                email: john.doe.updated@example.com
                phone: '+4915123456789'
                address: 123 Updated Address, Berlin, Germany
                availabilities:
                  - Monday
                  - Tuesday
      parameters:
        - name: promoter_id
          in: path
          schema:
            type: integer
          required: true
          example: '6'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete Promoter
      parameters:
        - name: promoter_id
          in: path
          schema:
            type: integer
          required: true
          example: '6'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/promoters/1/skills:
    post:
      tags:
        - default
      summary: Add Skill to Promoter
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                skill_id: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/promoter-groups/{promoter_group_id}:
    get:
      tags:
        - default
      summary: Show Promoter Group
      parameters:
        - name: promoter_group_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - default
      summary: Update Promoter Group
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Urban Adventure Guides
                description: >-
                  Ein Team von Experten für urbane Erkundungen, das Gruppen
                  durch Stadtabenteuer wie Street Art-Touren und
                  Nachtwanderungen führt.
                skill_ids:
                  - 3
                  - 4
                promoter_ids:
                  - 1
      parameters:
        - name: promoter_group_id
          in: path
          schema:
            type: integer
          required: true
          example: '6'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete Promoter Group
      parameters:
        - name: promoter_group_id
          in: path
          schema:
            type: integer
          required: true
          example: '6'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/promoter-groups/:
    post:
      tags:
        - default
      summary: Create Promoter Group
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Outdoor-Abenteuer-Guides
                description: >-
                  Ein Team von erfahrenen Spezialisten für Outdoor-Aktivitäten
                  wie Wandern, Camping und Survival-Training. Sie führen Gruppen
                  sicher durch anspruchsvolle Terrains und sorgen für ein
                  unvergessliches Erlebnis.
                skill_ids:
                  - 1
                  - 2
                promoter_ids:
                  - 3
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/skills/:
    get:
      tags:
        - default
      summary: List Skills
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Create Skill
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Latte-Art-Zertifikat
                description: >-
                  Fähigkeit, fortgeschrittene Latte-Art-Techniken zu beherrschen
                  und ein offizielles Zertifikat zu besitzen.
                promoter_group_ids:
                  - 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/skills/{skill_id}:
    get:
      tags:
        - default
      summary: Show Skill
      parameters:
        - name: skill_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - default
      summary: Update Skill
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Latte-Art-Zertifikat
                description: >-
                  Fähigkeit, fortgeschrittene Latte-Art-Techniken zu beherrschen
                  und ein offizielles Zertifikat zu besitzen.
                promoter_group_ids: []
      parameters:
        - name: skill_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete Skill
      parameters:
        - name: skill_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}